### PR TITLE
fix(karma-webpack): normalize paths (`windows`)

### LINKED ISSUE #350: TypeError: Path must be a string. Received [ 'js/main.spec.js',
x`｢wdm｣: wait until bundle finished: noop
03 09 2018 10:51:35.026:ERROR [karma]: TypeError: Path must be a string. Received [ 'js/main.spec.js',
  'css/tiscc.min.css',
  'js/main.spec.js.map',
  'css/tiscc.min.css.map' ]
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Plugin.<anonymous> (/builds/tis/tis/tiscommandcenter/node_modules/karma-webpack/lib/karma-webpack.js:262:68)
    at Plugin.readFile (/builds/tis/tis/tiscommandcenter/node_modules/karma-webpack/lib/karma-webpack.js:281:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

* Operating System: Windows 10
* Node Version: v8.11.3
* NPM Version: 6.4.0
* webpack Version: 4.17.1
* karma-webpack Version: 3.0.2

### Code

https://gist.github.com/casufi/f298bcab3f2f95a82616591446e380de

### PR DESCRIPTION
**Pull request by Teamop**
With #347 changes, now get error: `TypeError: Path must be a string. Received undefined`. After my research, there are 3 places will throw this error:

1. Two in the `readFile`, [L311](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L311), [L337](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L337), both are `this.outputs.get(file)`
--- the changes I made here is to map the file path to the entry path, so that can getting the file from the outputs. Example, changes from `test\unit\karma-test-shim` to `test/unit/karma-test-shim`

2. One in the `createPreprocesor` [L386](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L386), this line `webpackPlugin.outputs.get(filename);`
--- for this one, the file is already the real file path, if replaced with the webpack stats one, the karma web server cannot find the file 404.
Example here, changes from `C:/project/test/unit/karma-test-shim.js` to `C:\project\test\unit\karma-test-shim.js`

### Type

- [x] Fix

### Issues

- Fixes #350 

### SemVer

- [x] Patch

### CODE REVIEW

File: src/karma-webpack.js [hunk 1]
```diff
@@ -383,9 +387,6 @@ function createPreprocesor(/* config.basePath */ basePath, webpackPlugin) {
         throw err;
       }
 
-      const outputPath = webpackPlugin.outputs.get(filename);
-      file.path = path.join(basePath, outputPath);
```
Comment (rynclark) [inline src/karma-webpack.js]: How comes you removed this? It's needed to rewrite the asset path for karma to point to `.js` if the file extension was `.ts` for example

Comment (Teamop) [reply src/karma-webpack.js]: okay, but with this, just for simple js file, the karma web server will not find the file and throw 404

Comment (Teamop) [reply src/karma-webpack.js]: I tried to rewrite the file path like the above, but failed, so what do you think here should to do?

**Comment by thijstriemstra** [comment]
Seeing similar error after upgrading to RC1:

```
03 09 2018 20:55:24.766:ERROR [karma]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1158:7)
    at Plugin.<anonymous> (/home/foo/projects/bar/node_modules/karma-webpack/lib/karma-webpack.js:284:70)
    at Plugin.readFile (/home/foo/projects/bar/node_modules/karma-webpack/lib/karma-webpack.js:303:5)
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

File: src/karma-webpack.js (hunk 1 above)
Comment (Teamop) [reply src/karma-webpack.js]: Hi @rynclark , I tried to add this code back when testing with `.ts` file, but there's a problem, here `path.join(basePath, outputPath)` refers to the absolute path in the file system, so that 404, because `.js` doesn't exist at this `basePath`, so when replacing with path same as`webpackOptions.output.path = path.join(os.tmpdir(), '_karma_webpack_', indexPath, '/');`, still cannot find the compiled `.js` file

File: src/karma-webpack.js [hunk 2]
```diff
@@ -308,7 +308,7 @@ Plugin.prototype.readFile = function(file, callback) {
               os.tmpdir(),
               '_karma_webpack_',
               String(idx),
-              this.outputs.get(file)
+              this.outputs.get(file.replace(/\\/g, '/'))
```
Comment (michael-ciniawsky) [inline src/karma-webpack.js]: Please move this into it's own helper 

```js
const nomalize = (file) => file.replace(/\\/g, '/')
```

File: src/karma-webpack.js (hunk 1 above)
Comment (michael-ciniawsky) [reply src/karma-webpack.js]: Could we move discussion about this into another PR and first of all fix the file path normalization issue as this seems to be critical?

Comment (Teamop) [reply src/karma-webpack.js]: @michael-ciniawsky, but as my test, for this part, even just fix the file path normalization issue, still cannot work with 404 error.

Comment (michael-ciniawsky) [reply src/karma-webpack.js]: I see, can't confidently comment on what went wrong here, we may need to revert this for now then... :)

If you remove the `this.outputs` part it works, so other changes made recently e.g `this.entries` are not affected or is there a general problem which this approach?

Comment (michael-ciniawsky) [reply src/karma-webpack.js]: This also isn't possibly related to #338 ?

Comment (Teamop) [reply src/karma-webpack.js]: Right now, the current changes in this PR can work for me for `.js` file, but as @rynclark said, if it's for `.ts` file, this change cannot work. So as you can see the comment above, I tried to add this back, but there's a issue that I haven't found a solution yet.
I will try with #338 later.

Comment (Teamop) [reply src/karma-webpack.js]: Right now, this can work for both `.js` and `.ts` based on my test. The only different with #353, is L393, add normalize again.

Comment (Teamop) [reply src/karma-webpack.js]: I tried with v3.0.3, still needs this L393 changes which normalize the path again. I have opened a PR #354  for 3.0. @michael-ciniawsky

Comment (michael-ciniawsky) [reply src/karma-webpack.js]: @Teamop Thx. Do the changes introduced by https://github.com/webpack-contrib/karma-webpack/commit/ab4dde9a7b859e815e11925a0f5cc5c986360264 still cause any regressions (for you)? If so I may need to revert them for now. 

This PR is ready I assume ? :)

Comment (Teamop) [reply src/karma-webpack.js]: this PR is ready, with this changs, I have no issues.

Comment (michael-ciniawsky) [reply src/karma-webpack.js]: Sry 🙏 I skipped over https://github.com/webpack-contrib/karma-webpack/pull/351/files#r215968728

Comment (Teamop) [reply src/karma-webpack.js]: np, thanks @michael-ciniawsky
