### PR TITLE
fix(karma-webpack): correctly coalesce `idx` (`{Number}`) in filepaths

### LINKED ISSUE #286: TypeError: Path must be a string
**I'm submitting a bug report**

**Webpack version:**
3.10.0

**Webpack Karma version**:
2.0.9

**Karma version**:
1.7.1

**Please tell us about your environment:**
OSX 10.12.6

**Browser:** [Phantom XX | Chrome XX | Firefox XX | IE XX | Safari XX | Other XX]
Phantom | Chrome 64

**Current behavior:**
Karma fails to run, throwing a TypeError

**Expected/desired behavior:**
Karma runs without errors

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Use karma-webpack 2.0.8-2.0.9 and a TypeError will be thrown:

```
TypeError: Path must be a string. Received 0
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at /Users/jared.nyman/project/node_modules/karma-webpack/lib/karma-webpack.js:203:45
    at /Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:246:17
    at /Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:122:13
    at _each (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:46:13)
    at async.each (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:245:13)
    at Object.map (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:216:23)
    at Object.async.times (/Users/jared.nyman/project/node_modules/karma-webpack/node_modules/async/lib/async.js:1040:22)
    at Plugin.<anonymous> (/Users/jared.nyman/project/node_modules/karma-webpack/lib/karma-webpack.js:197:13)
    at Plugin.readFile (/Users/jared.nyman/project/node_modules/karma-webpack/lib/karma-webpack.js:239:5)
```

It looks like 0616dda489d07f6a9bc3def1778dcef601411821 introduced a subtle change:
`path.join(os.tmpdir(), '_karma_webpack_', idx, file.replace(/\\/g, '/')`

`idx` is no longer being coalesced into a string, which causes path.join to bomb

### PR DESCRIPTION
**Pull request by Pwntastic**
fix: convert index to string before passing to path.join to avoid TypeError

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
#286 

**What is the new behavior?**
Converts an index to a string before it gets passed into path.join. It was previously being coalesced before 0616dda489d07f6a9bc3def1778dcef601411821

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the following...

* Impact:
* Migration path for existing applications:
* Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

File: src/karma-webpack.js [hunk 1]
```diff
@@ -198,7 +198,7 @@ Plugin.prototype.readFile = function(file, callback) {
   var doRead = function() {
     if (optionsCount > 1) {
       async.times(optionsCount, function(idx, callback) {
-        middleware.fileSystem.readFile(path.join(os.tmpdir(), '_karma_webpack_', idx, file.replace(/\\/g, '/')), callback)
+        middleware.fileSystem.readFile(path.join(os.tmpdir(), '_karma_webpack_', idx.toString(), file.replace(/\\/g, '/')), callback)
```
Comment (michael-ciniawsky) [inline src/karma-webpack.js]: `String(idx)` or coalesce it by changing it back to how it was handled [before](https://github.com/webpack-contrib/karma-webpack/commit/0616dda489d07f6a9bc3def1778dcef601411821#diff-1bc56a1b4b855af7b16012fcf5210059L200) https://github.com/webpack-contrib/karma-webpack/commit/0616dda489d07f6a9bc3def1778dcef601411821 (concat) please :)

Comment (Pwntastic) [reply src/karma-webpack.js]: You got it
